### ISSUE TITLE
test compile on Windows

### ISSUE THREAD

**Issue by SamBkamp** [SamBkamp/Aladdin#50]

**Comment by leon-th** [comment]
As far as I know:   
For the libraries:    

- `sys/socket.h`
- `netdb.h`
- `unistd.h`

there are alternatives for windows:   

- `Winsock2.h`
- `windows.h`

The syntax should be the same.   
The remaining libraries are the same.   
Except for:

- `pthread.h` 
- `ncurses.h` 

there is no direct replacement for these.   
I was unable to run a complete build, due to the missing dependencies

**Comment by SamBkamp** [comment]
okay, it seems like using C may not be the best choice for a windows port for Aladdin. Perhaps we can look into something like [mingw](http://www.mingw.org/), it runs can run in Windows but it does require you to compile and run in a virtual Linux environment. It will work but it is a little bit of a hassle. Thanks for looking into the topic.
